image:
    - Visual Studio 2015
#    - Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\comms_champion
shallow_clone: true             

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

#environment:
#    matrix:
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#          TOOLCHAIN: msvc14
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#          TOOLCHAIN: msvc15
          

install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin

build_script:
    - mkdir build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - cd build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DBOOST_ROOT="C:\Libraries\boost_1_65_1" -DBoost_USE_STATIC_LIBS=ON -DCOMMSDSL_QT_DIR=%QTDIR%
    - set PATH=%PATH%;c:\projects\commsdsl\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%\lib\src
    - nmake 

test_script:
    - ctest 



