image:
    - Visual Studio 2015
#    - Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\commsdsl
shallow_clone: true             

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

#environment:
#    matrix:
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#          TOOLCHAIN: msvc14
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#          TOOLCHAIN: msvc15
          

install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin

build_script:
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - mkdir %BUILD_DIR%
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DBOOST_ROOT="C:\Libraries\boost_1_65_1" -DBoost_USE_STATIC_LIBS=ON -DCOMMSDSL_QT_DIR=%QTDIR%
    - set PATH=%BUILD_DIR%\lib\src;%PATH%
    - echo Building in %BUILD_DIR%
    - echo PATH = %PATH%
    - nmake

test_script:
    - ctest 



