image:
    - Visual Studio 2015
    - Visual Studio 2017

init:
    - git config --global core.autocrlf input

notifications:
  - provider: Email
    to:
      - arobenko@gmail.com
    on_build_failure: true
    on_build_status_changed: true

clone_folder: c:\projects\commsdsl
shallow_clone: true             

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - CPP_STD: 11
          QT_VER: 5.6.3
        - CPP_STD: 11
          QT_VER: 5.6.3
          CC_TAG: v1.0
        - CPP_STD: 14
          QT_VER: 5.6.3

install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin

build_script:
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - mkdir %BUILD_DIR%
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" \
        -DBOOST_ROOT="C:\Libraries\boost_1_65_1" -DBoost_USE_STATIC_LIBS=ON \
        -DCOMMSDSL_QT_DIR=%QTDIR% -DCOMMSDSL_TESTS_CXX_STANDARD=%CPP_STD% \
        -DCC_TAG=%CC_TAG%
    - set PATH=%BUILD_DIR%\lib\src;%PATH%
    - echo Building in %BUILD_DIR%
    - echo PATH = %PATH%
    - nmake

test_script:
    - ctest 



